### ISSUE TITLE
Old googleapis dependency specified in the doc

### ISSUE THREAD

**Issue by raynor85** [gsuitedevs/node-samples#71]
## Expected Behavior
The API installed by npm is outdated, so in the doc it should be written something like:
```
npm install googleapis --save
```

## Actual Behavior
The API installed is an old one, but the online documentation should always refer to the most updated one.
```
npm install googleapis@27 --save
```

**Comment by zipzit** [comment]
Me too.  [NPM googleapis is up to version 39.2](https://www.npmjs.com/package/googleapis)

Wny are we using version 27?

**Comment by sqrrrl** [comment]
The node client lib changes major versions very frequently and often has breaking changes in major versions. To put things in perspective, version 27 is only a year old and there have been 12 major releases for the client in the past year. That's a lot of updates to keep up to date with.

Unfortunately we just don't have the tools and processes in place right now to automatically update and test the dependencies for every sample. Something I'd like to have at some point, but we're just not there right now. And it's safer for us to pin the version for a sample to a known working version rather than risk the samples breaking when the client library is updated.

You're of course welcome to use a more recent version of the client in your own apps.

**Comment by raynor85** [comment]
Maybe specify in the doc what you just said, because it might happen that
people follow the QuickStart guide ignoring that they are installing an
outdated version. It happened to me, and I was trying to use some features
from most updated version. I spent 1 hour before figuring out why these
features were not working

**Comment by zipzit** [comment]
As I wade thru the details, I'm finding out there are other changes to the auth key / credential generation stuff that is problematic here.  Authentication values don't contain content that matches up to the google sheets api v4 samples.  Ref: https://stackoverflow.com/questions/55839566/unable-to-use-google-sheets-api-cant-generate-correct-credential-elements.  

Apparently you have to 'fake it' . In order to use the call `authorize(credentials, callback)` for Google sheets API v4,  I ended up creating my own credentials.json file containing 

```
{
    "project_id": "xxx-sheets-api",
    "client_email": "xyz@xxx.iam.gserviceaccount.com",
    "client_id": "xxx.apps.googleusercontent.com",
    "auth_uri": "https://accounts.google.com/o/oauth2/auth",
    "token_uri": "https://oauth2.googleapis.com/token",
    "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
    "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/ccinema-google-sheets-api%40ccinema-sheets-api.iam.gserviceaccount.com",
    "client_secret": "xxx",
    "redirect_uris": [
        "urn:ietf:wg:oauth:2.0:oob",
        "http://localhost"
    ]
}
```

My guess is, once the Google credential generation stuff stabilizes, some content re-write will be required (beyond the dependency issue in this topic.)

**Comment by zipzit** [comment]
Update:  I'm working on NodeJS server, with Append mode

 ```
const res = await sheets.spreadsheets.values.append({
                spreadsheetId: 'xxx',    // from the spreadsheet URL
                range: range,
                valueInputOption: "RAW",  // was 'USER_ENTERED'
                insertDataOption: "INSERT_ROWS",   
                resource: {
                    values: [valueArray]
                },
            });
```

for reference, my "valueArray" is a simple array.  I'm updating one row at a time, but you do have to wrap the simple array with array brackets...

Note: when using GoogleAPI v27, I was getting 

> error (node:4868) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'data' of undefined

The app functions okay in that data is pushed to the Google sheet, but the error problematic.  If I delete the line        ` "googleapis": "27.0.0",` from package.json (save the file), then `$ npm install googleapis --save` I can see version 39 getting installed.  Rerun the server, all fixed.  No more error message upon Google sheet append operation. (Note: I did NOT have the issue when I was simply reading data from the Google Sheet.

Apparently size does matter. :)
