### ISSUE TITLE
While creating a google doc file through cmd the open module is not found by the system

### ISSUE THREAD

**Issue by divya14chhabra** [gsuitedevs/node-samples#80]
## Expected Behavior
The file should be runned and should have created a file in GoogleDrive

## Actual Behavior

The code is giving error that Open Module is not found

##Error
![issue](https://user-images.githubusercontent.com/41488664/61272226-4257f500-a7c4-11e9-9d60-dd40711fbd9d.png)

**Comment by sqrrrl** [comment]
This doesn't appear to be any of the samples in this repo, but your own code. This issue tracker is only for issues related to the samples here. For general help with the Docs API, see https://developers.google.com/docs/api/support

From the error, it sounds like the issue is you're requiring a module that you don't have installed. Where you have your package.json file, try:

```
npm install --save open
```
